- name: Deploy to EC2
  uses: appleboy/ssh-action@v1
  with:
    host: ${{ secrets.EC2_HOST }}
    username: ${{ secrets.EC2_USER }}
    key: ${{ secrets.EC2_KEY }}
    timeout: 200s
    command_timeout: 200s
    script: |
      cd ~/restaurant-app || git clone https://github.com/Kavishka15055/Good-Food-Wbe-site.git restaurant-app
      cd restaurant-app
      docker-compose down
      docker-compose up -d --build
